import { describe, expect, it } from "vitest";
import type { WorkflowContext } from "./fetchWorkflowContexts";
import {
  biomeFormat,
  generateTypes,
  stableKeyToTypeName,
} from "./generateTypes";

const HEADER = `// This file was auto-generated by @prismatic-io/embedded generate-types.
// Do not edit this file manually.`;

const formatExpected = (body: string) =>
  biomeFormat(`${HEADER}\n\nexport {}\n\n${body}`);

describe("generateTypes", () => {
  it("produces an empty WorkflowContexts interface when given no contexts", async () => {
    const result = await generateTypes([]);
    const expected = await formatExpected(`
declare module "@prismatic-io/embedded" {
  interface WorkflowContexts {}
}
`);
    expect(result).toEqual(expected);
  });

  it("generates a typed context from a simple schema", async () => {
    const contexts: WorkflowContext[] = [
      {
        stableKey: "my-workflow",
        contextSchema: {
          type: "object",
          properties: {
            name: { type: "string" },
          },
          required: ["name"],
        },
      },
    ];

    const result = await generateTypes(contexts);
    const expected = await formatExpected(`
declare module "@prismatic-io/embedded" {
  interface MyWorkflowContext {
    name: string;
  }

  interface WorkflowContexts {
    "my-workflow": MyWorkflowContext;
  }
}
`);
    expect(result).toEqual(expected);
  });

  it("generates multiple contexts", async () => {
    const contexts: WorkflowContext[] = [
      {
        stableKey: "first",
        contextSchema: {
          type: "object",
          properties: { a: { type: "string" } },
        },
      },
      {
        stableKey: "second",
        contextSchema: {
          type: "object",
          properties: { b: { type: "number" } },
        },
      },
    ];

    const result = await generateTypes(contexts);
    const expected = await formatExpected(`
declare module "@prismatic-io/embedded" {
  interface FirstContext {
    a?: string;
  }

  interface SecondContext {
    b?: number;
  }

  interface WorkflowContexts {
    first: FirstContext;
    second: SecondContext;
  }
}
`);
    expect(result).toEqual(expected);
  });

  it.each([
    ["kebab-case", "KebabCaseContext"],
    ["snake_case", "SnakeCaseContext"],
    ["dot.delimited", "DotDelimitedContext"],
    ["alreadyPascal", "AlreadyPascalContext"],
    ["multi--separator", "MultiSeparatorContext"],
  ])("converts stableKey %s to type name %s", (stableKey, expected) => {
    expect(stableKeyToTypeName(stableKey)).toEqual(expected);
  });

  it("handles nested object schemas", async () => {
    const contexts: WorkflowContext[] = [
      {
        stableKey: "nested",
        contextSchema: {
          type: "object",
          properties: {
            address: {
              type: "object",
              properties: {
                street: { type: "string" },
                zip: { type: "string" },
              },
              required: ["street"],
            },
          },
          required: ["address"],
        },
      },
    ];

    const result = await generateTypes(contexts);
    const expected = await formatExpected(`
declare module "@prismatic-io/embedded" {
  interface NestedContext {
    address: {
      street: string;
      zip?: string;
    };
  }

  interface WorkflowContexts {
    nested: NestedContext;
  }
}
`);
    expect(result).toEqual(expected);
  });

  it("marks properties without required as optional", async () => {
    const contexts: WorkflowContext[] = [
      {
        stableKey: "optional-fields",
        contextSchema: {
          type: "object",
          properties: {
            required_field: { type: "string" },
            optional_field: { type: "number" },
          },
          required: ["required_field"],
        },
      },
    ];

    const result = await generateTypes(contexts);
    const expected = await formatExpected(`
declare module "@prismatic-io/embedded" {
  interface OptionalFieldsContext {
    required_field: string;
    optional_field?: number;
  }

  interface WorkflowContexts {
    "optional-fields": OptionalFieldsContext;
  }
}
`);
    expect(result).toEqual(expected);
  });

  it("disambiguates colliding type names with numeric suffixes", async () => {
    const contexts: WorkflowContext[] = [
      {
        stableKey: "my-workflow",
        contextSchema: {
          type: "object",
          properties: { a: { type: "string" } },
        },
      },
      {
        stableKey: "myWorkflow",
        contextSchema: {
          type: "object",
          properties: { b: { type: "string" } },
        },
      },
    ];

    const result = await generateTypes(contexts);
    const expected = await formatExpected(`
declare module "@prismatic-io/embedded" {
  interface MyWorkflowContext1 {
    a?: string;
  }

  interface MyWorkflowContext2 {
    b?: string;
  }

  interface WorkflowContexts {
    "my-workflow": MyWorkflowContext1;
    myWorkflow: MyWorkflowContext2;
  }
}
`);
    expect(result).toEqual(expected);
  });

  it("does not suffix when there is no collision", async () => {
    const contexts: WorkflowContext[] = [
      {
        stableKey: "my-workflow",
        contextSchema: {
          type: "object",
          properties: { a: { type: "string" } },
        },
      },
      {
        stableKey: "something-else",
        contextSchema: {
          type: "object",
          properties: { b: { type: "string" } },
        },
      },
    ];

    const result = await generateTypes(contexts);
    const expected = await formatExpected(`
declare module "@prismatic-io/embedded" {
  interface MyWorkflowContext {
    a?: string;
  }

  interface SomethingElseContext {
    b?: string;
  }

  interface WorkflowContexts {
    "my-workflow": MyWorkflowContext;
    "something-else": SomethingElseContext;
  }
}
`);
    expect(result).toEqual(expected);
  });
});
