import { execFile } from "node:child_process";
import { compile } from "json-schema-to-typescript";
import type { WorkflowContext } from "./fetchWorkflowContexts";

export const biomeFormat = (source: string): Promise<string> =>
  new Promise((resolve, reject) => {
    const child = execFile(
      "npx",
      ["biome", "format", "--stdin-file-path=generated.ts"],
      (error, stdout, stderr) => {
        if (error) {
          reject(new Error(`biome format failed: ${stderr}`));
          return;
        }
        resolve(stdout);
      },
    );
    child.stdin?.write(source);
    child.stdin?.end();
  });

const GENERATED_HEADER = `// This file was auto-generated by @prismatic-io/embedded generate-types.
// Do not edit this file manually.`;

// A top-level export is required so TypeScript treats the file as a module.
// Without it, `declare module` becomes an ambient module declaration that
// replaces the module's types instead of augmenting them.
const MODULE_EXPORT = "export {};";

export const stableKeyToTypeName = (stableKey: string): string =>
  `${stableKey
    .replace(/[^a-zA-Z0-9]+(.)/g, (_, c) => c.toUpperCase())
    .replace(/^./, (c) => c.toUpperCase())}Context`;

const deduplicateTypeNames = (
  contexts: WorkflowContext[],
): Map<string, string> => {
  const nameToKeys = new Map<string, string[]>();
  for (const ctx of contexts) {
    const name = stableKeyToTypeName(ctx.stableKey);
    const existing = nameToKeys.get(name);
    if (existing) {
      existing.push(ctx.stableKey);
    } else {
      nameToKeys.set(name, [ctx.stableKey]);
    }
  }

  const keyToName = new Map<string, string>();
  for (const [name, keys] of nameToKeys) {
    if (keys.length === 1) {
      keyToName.set(keys[0], name);
    } else {
      for (let i = 0; i < keys.length; i++) {
        keyToName.set(keys[i], `${name}${i + 1}`);
      }
    }
  }

  return keyToName;
};

const generateContextType = async (
  context: WorkflowContext,
  typeName: string,
): Promise<{
  stableKey: string;
  typeName: string;
  interfaceString: string;
}> => {
  const interfaceString = await compile(context.contextSchema, typeName, {
    bannerComment: "",
    additionalProperties: false,
  });

  return { stableKey: context.stableKey, typeName, interfaceString };
};

export const generateTypes = async (
  contexts: WorkflowContext[],
): Promise<string> => {
  if (contexts.length === 0) {
    return biomeFormat(
      `${GENERATED_HEADER}\n\n${MODULE_EXPORT}\n\ndeclare module "@prismatic-io/embedded" {\n  interface WorkflowContexts {}\n}\n`,
    );
  }

  const typeNames = deduplicateTypeNames(contexts);
  const generated = await Promise.all(
    contexts.map((ctx) =>
      generateContextType(ctx, typeNames.get(ctx.stableKey)!),
    ),
  );

  const interfaces = generated
    .map((g) => g.interfaceString.replace(/^export /gm, ""))
    .join("\n");

  const contextEntries = generated
    .map((g) => `    "${g.stableKey}": ${g.typeName};`)
    .join("\n");

  const output = `${GENERATED_HEADER}

${MODULE_EXPORT}

declare module "@prismatic-io/embedded" {
${interfaces}
  interface WorkflowContexts {
${contextEntries}
  }
}
`;

  return biomeFormat(output);
};
