/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ExamplesBasicEmbeddedMarketplaceRouteImport } from './routes/examples/basic-embedded-marketplace'
import { Route as ExamplesBasicMarketplacePopoverRouteImport } from './routes/examples/basic-marketplace-popover'
import { Route as ExamplesChatBotRouteImport } from './routes/examples/chat-bot'
import { Route as ExamplesConnectionsRouteImport } from './routes/examples/connections'
import { Route as ExamplesCustomMarketplaceUiRouteImport } from './routes/examples/custom-marketplace-ui'
import { Route as ExamplesDashboardRouteImport } from './routes/examples/dashboard'
import { Route as ExamplesEditInstanceConfigurationRouteImport } from './routes/examples/edit-instance-configuration'
import { Route as ExamplesScreenConfigurationRouteImport } from './routes/examples/screen-configuration'
import { Route as ExamplesTranslationsRouteImport } from './routes/examples/translations'
import { Route as PlaceholderAccountsRouteImport } from './routes/placeholder/accounts'
import { Route as PlaceholderContactsRouteImport } from './routes/placeholder/contacts'
import { Route as PlaceholderLeadsRouteImport } from './routes/placeholder/leads'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ExamplesBasicEmbeddedMarketplaceRoute =
  ExamplesBasicEmbeddedMarketplaceRouteImport.update({
    id: '/examples/basic-embedded-marketplace',
    path: '/examples/basic-embedded-marketplace',
    getParentRoute: () => rootRouteImport,
  } as any)
const ExamplesBasicMarketplacePopoverRoute =
  ExamplesBasicMarketplacePopoverRouteImport.update({
    id: '/examples/basic-marketplace-popover',
    path: '/examples/basic-marketplace-popover',
    getParentRoute: () => rootRouteImport,
  } as any)
const ExamplesChatBotRoute = ExamplesChatBotRouteImport.update({
  id: '/examples/chat-bot',
  path: '/examples/chat-bot',
  getParentRoute: () => rootRouteImport,
} as any)
const ExamplesConnectionsRoute = ExamplesConnectionsRouteImport.update({
  id: '/examples/connections',
  path: '/examples/connections',
  getParentRoute: () => rootRouteImport,
} as any)
const ExamplesCustomMarketplaceUiRoute =
  ExamplesCustomMarketplaceUiRouteImport.update({
    id: '/examples/custom-marketplace-ui',
    path: '/examples/custom-marketplace-ui',
    getParentRoute: () => rootRouteImport,
  } as any)
const ExamplesDashboardRoute = ExamplesDashboardRouteImport.update({
  id: '/examples/dashboard',
  path: '/examples/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ExamplesEditInstanceConfigurationRoute =
  ExamplesEditInstanceConfigurationRouteImport.update({
    id: '/examples/edit-instance-configuration',
    path: '/examples/edit-instance-configuration',
    getParentRoute: () => rootRouteImport,
  } as any)
const ExamplesScreenConfigurationRoute =
  ExamplesScreenConfigurationRouteImport.update({
    id: '/examples/screen-configuration',
    path: '/examples/screen-configuration',
    getParentRoute: () => rootRouteImport,
  } as any)
const ExamplesTranslationsRoute = ExamplesTranslationsRouteImport.update({
  id: '/examples/translations',
  path: '/examples/translations',
  getParentRoute: () => rootRouteImport,
} as any)
const PlaceholderAccountsRoute = PlaceholderAccountsRouteImport.update({
  id: '/placeholder/accounts',
  path: '/placeholder/accounts',
  getParentRoute: () => rootRouteImport,
} as any)
const PlaceholderContactsRoute = PlaceholderContactsRouteImport.update({
  id: '/placeholder/contacts',
  path: '/placeholder/contacts',
  getParentRoute: () => rootRouteImport,
} as any)
const PlaceholderLeadsRoute = PlaceholderLeadsRouteImport.update({
  id: '/placeholder/leads',
  path: '/placeholder/leads',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/examples/basic-embedded-marketplace': typeof ExamplesBasicEmbeddedMarketplaceRoute
  '/examples/basic-marketplace-popover': typeof ExamplesBasicMarketplacePopoverRoute
  '/examples/chat-bot': typeof ExamplesChatBotRoute
  '/examples/connections': typeof ExamplesConnectionsRoute
  '/examples/custom-marketplace-ui': typeof ExamplesCustomMarketplaceUiRoute
  '/examples/dashboard': typeof ExamplesDashboardRoute
  '/examples/edit-instance-configuration': typeof ExamplesEditInstanceConfigurationRoute
  '/examples/screen-configuration': typeof ExamplesScreenConfigurationRoute
  '/examples/translations': typeof ExamplesTranslationsRoute
  '/placeholder/accounts': typeof PlaceholderAccountsRoute
  '/placeholder/contacts': typeof PlaceholderContactsRoute
  '/placeholder/leads': typeof PlaceholderLeadsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/examples/basic-embedded-marketplace': typeof ExamplesBasicEmbeddedMarketplaceRoute
  '/examples/basic-marketplace-popover': typeof ExamplesBasicMarketplacePopoverRoute
  '/examples/chat-bot': typeof ExamplesChatBotRoute
  '/examples/connections': typeof ExamplesConnectionsRoute
  '/examples/custom-marketplace-ui': typeof ExamplesCustomMarketplaceUiRoute
  '/examples/dashboard': typeof ExamplesDashboardRoute
  '/examples/edit-instance-configuration': typeof ExamplesEditInstanceConfigurationRoute
  '/examples/screen-configuration': typeof ExamplesScreenConfigurationRoute
  '/examples/translations': typeof ExamplesTranslationsRoute
  '/placeholder/accounts': typeof PlaceholderAccountsRoute
  '/placeholder/contacts': typeof PlaceholderContactsRoute
  '/placeholder/leads': typeof PlaceholderLeadsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/examples/basic-embedded-marketplace': typeof ExamplesBasicEmbeddedMarketplaceRoute
  '/examples/basic-marketplace-popover': typeof ExamplesBasicMarketplacePopoverRoute
  '/examples/chat-bot': typeof ExamplesChatBotRoute
  '/examples/connections': typeof ExamplesConnectionsRoute
  '/examples/custom-marketplace-ui': typeof ExamplesCustomMarketplaceUiRoute
  '/examples/dashboard': typeof ExamplesDashboardRoute
  '/examples/edit-instance-configuration': typeof ExamplesEditInstanceConfigurationRoute
  '/examples/screen-configuration': typeof ExamplesScreenConfigurationRoute
  '/examples/translations': typeof ExamplesTranslationsRoute
  '/placeholder/accounts': typeof PlaceholderAccountsRoute
  '/placeholder/contacts': typeof PlaceholderContactsRoute
  '/placeholder/leads': typeof PlaceholderLeadsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/examples/basic-embedded-marketplace'
    | '/examples/basic-marketplace-popover'
    | '/examples/chat-bot'
    | '/examples/connections'
    | '/examples/custom-marketplace-ui'
    | '/examples/dashboard'
    | '/examples/edit-instance-configuration'
    | '/examples/screen-configuration'
    | '/examples/translations'
    | '/placeholder/accounts'
    | '/placeholder/contacts'
    | '/placeholder/leads'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/examples/basic-embedded-marketplace'
    | '/examples/basic-marketplace-popover'
    | '/examples/chat-bot'
    | '/examples/connections'
    | '/examples/custom-marketplace-ui'
    | '/examples/dashboard'
    | '/examples/edit-instance-configuration'
    | '/examples/screen-configuration'
    | '/examples/translations'
    | '/placeholder/accounts'
    | '/placeholder/contacts'
    | '/placeholder/leads'
  id:
    | '__root__'
    | '/'
    | '/examples/basic-embedded-marketplace'
    | '/examples/basic-marketplace-popover'
    | '/examples/chat-bot'
    | '/examples/connections'
    | '/examples/custom-marketplace-ui'
    | '/examples/dashboard'
    | '/examples/edit-instance-configuration'
    | '/examples/screen-configuration'
    | '/examples/translations'
    | '/placeholder/accounts'
    | '/placeholder/contacts'
    | '/placeholder/leads'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ExamplesBasicEmbeddedMarketplaceRoute: typeof ExamplesBasicEmbeddedMarketplaceRoute
  ExamplesBasicMarketplacePopoverRoute: typeof ExamplesBasicMarketplacePopoverRoute
  ExamplesChatBotRoute: typeof ExamplesChatBotRoute
  ExamplesConnectionsRoute: typeof ExamplesConnectionsRoute
  ExamplesCustomMarketplaceUiRoute: typeof ExamplesCustomMarketplaceUiRoute
  ExamplesDashboardRoute: typeof ExamplesDashboardRoute
  ExamplesEditInstanceConfigurationRoute: typeof ExamplesEditInstanceConfigurationRoute
  ExamplesScreenConfigurationRoute: typeof ExamplesScreenConfigurationRoute
  ExamplesTranslationsRoute: typeof ExamplesTranslationsRoute
  PlaceholderAccountsRoute: typeof PlaceholderAccountsRoute
  PlaceholderContactsRoute: typeof PlaceholderContactsRoute
  PlaceholderLeadsRoute: typeof PlaceholderLeadsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/examples/basic-embedded-marketplace': {
      id: '/examples/basic-embedded-marketplace'
      path: '/examples/basic-embedded-marketplace'
      fullPath: '/examples/basic-embedded-marketplace'
      preLoaderRoute: typeof ExamplesBasicEmbeddedMarketplaceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/examples/basic-marketplace-popover': {
      id: '/examples/basic-marketplace-popover'
      path: '/examples/basic-marketplace-popover'
      fullPath: '/examples/basic-marketplace-popover'
      preLoaderRoute: typeof ExamplesBasicMarketplacePopoverRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/examples/chat-bot': {
      id: '/examples/chat-bot'
      path: '/examples/chat-bot'
      fullPath: '/examples/chat-bot'
      preLoaderRoute: typeof ExamplesChatBotRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/examples/connections': {
      id: '/examples/connections'
      path: '/examples/connections'
      fullPath: '/examples/connections'
      preLoaderRoute: typeof ExamplesConnectionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/examples/custom-marketplace-ui': {
      id: '/examples/custom-marketplace-ui'
      path: '/examples/custom-marketplace-ui'
      fullPath: '/examples/custom-marketplace-ui'
      preLoaderRoute: typeof ExamplesCustomMarketplaceUiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/examples/dashboard': {
      id: '/examples/dashboard'
      path: '/examples/dashboard'
      fullPath: '/examples/dashboard'
      preLoaderRoute: typeof ExamplesDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/examples/edit-instance-configuration': {
      id: '/examples/edit-instance-configuration'
      path: '/examples/edit-instance-configuration'
      fullPath: '/examples/edit-instance-configuration'
      preLoaderRoute: typeof ExamplesEditInstanceConfigurationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/examples/screen-configuration': {
      id: '/examples/screen-configuration'
      path: '/examples/screen-configuration'
      fullPath: '/examples/screen-configuration'
      preLoaderRoute: typeof ExamplesScreenConfigurationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/examples/translations': {
      id: '/examples/translations'
      path: '/examples/translations'
      fullPath: '/examples/translations'
      preLoaderRoute: typeof ExamplesTranslationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/placeholder/accounts': {
      id: '/placeholder/accounts'
      path: '/placeholder/accounts'
      fullPath: '/placeholder/accounts'
      preLoaderRoute: typeof PlaceholderAccountsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/placeholder/contacts': {
      id: '/placeholder/contacts'
      path: '/placeholder/contacts'
      fullPath: '/placeholder/contacts'
      preLoaderRoute: typeof PlaceholderContactsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/placeholder/leads': {
      id: '/placeholder/leads'
      path: '/placeholder/leads'
      fullPath: '/placeholder/leads'
      preLoaderRoute: typeof PlaceholderLeadsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ExamplesBasicEmbeddedMarketplaceRoute: ExamplesBasicEmbeddedMarketplaceRoute,
  ExamplesBasicMarketplacePopoverRoute: ExamplesBasicMarketplacePopoverRoute,
  ExamplesChatBotRoute: ExamplesChatBotRoute,
  ExamplesConnectionsRoute: ExamplesConnectionsRoute,
  ExamplesCustomMarketplaceUiRoute: ExamplesCustomMarketplaceUiRoute,
  ExamplesDashboardRoute: ExamplesDashboardRoute,
  ExamplesEditInstanceConfigurationRoute:
    ExamplesEditInstanceConfigurationRoute,
  ExamplesScreenConfigurationRoute: ExamplesScreenConfigurationRoute,
  ExamplesTranslationsRoute: ExamplesTranslationsRoute,
  PlaceholderAccountsRoute: PlaceholderAccountsRoute,
  PlaceholderContactsRoute: PlaceholderContactsRoute,
  PlaceholderLeadsRoute: PlaceholderLeadsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
